services:

  book-topics-api:
    image: us-central1-docker.pkg.dev/books-us/hw-airnd/hw-airnd-book-topics
    pull_policy: always
    environment:
      PORT: 5050
      API_DATA_DIR: "/app/data"
    ports:
      - "5050:5050"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.book-topics-api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.book-topics-api.entrypoints=web"
      - "traefik.http.services.book-topics-api.loadbalancer.server.port=5050"
    volumes:
      - './data:/app/data'

  traefik:
    image: "traefik:v3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
#      - "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
#      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
#      - "--certificatesresolvers.myresolver.acme.email=yevhenii.stepanenko@makeheadway.com"
#      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
#      - "443:443"
      - "8080:8080"
    volumes:
#      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"